### ISSUE TITLE
When disabling a link, should send STOP and UNBIND to provider before closing connection

### ISSUE THREAD

**Issue by AdamElliott-AB** [yamcs/yamcs-sle#8]

**Comment by merose** [comment]
I have submitted a pull request to fix this. It is somewhat brute-force – there may be a more elegant way to handle this. Also, this only fixes the shutdown for RAF and RCF services. The same sort of fix must be applied to the Forward CLTU service as well. It might be better to handle this in jsle so that a single fix is sufficient for all of RAF, RCF, and FCLTU.

**Comment by xpromache** [comment]
On Mon, May 24, 2021 at 10:11 PM Mark Rose ***@***.***> wrote:

> It might be better to handle this in jsle so that a single fix is
> sufficient for all of RAF, RCF, and FCLTU.
>

I agree, we should have this in the jsle, perhaps modifying the
current AbstractServiceUserHandler#shutdown method with an argument
graceful:

    /**
     * Closes a SLE connection, possibly by first unbinding and stopping
the SLE link.
     *
     * @param graceful
     *            if true, the SLE link will be first unbound and then
stopped if necessary. If false, the TCP
     *            connection will be closed regardless of the state of the
SLE link.
     */
    public void shutdown(boolean graceful) ;

Note that the AbstractServiceUserHandler serializes all operations via
channelHandlerContext.executor().execute(...) which should avoid getting
into an inconsistent state when parallel calls are made.

And since you are at it, you can also add an argument for the unbind method
so the user can specify the reason for the unbind and then we can use it
from yamcs-sle...

Thanks!
nicolae

**Comment by xpromache** [comment]
Finally I have implemented it more in line with the original pull request than with my idea above (because the jsle did not include any compound operation so I thought it is not good to introduce now a graceful shutdown which will do multiple SLE calls).
